apiVersion: apps/v1
kind: Deployment
metadata:
  name: trojanwall-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trojan-wall
  template:
    metadata:
      labels:
      
        app: trojan-wall
    spec:
      containers:
      - name: trojan-wall
        image: arbabu/trojan-wall:v2
        ports:
        - containerPort: 80
---

#Service
kind: Service
apiVersion: v1
metadata:
  name: trojanwall-service
spec:
  selector:
    app: trojan-wall
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort  #internal loadbalancer



  